# Generated by Django 3.0.8 on 2020-08-01 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('employee', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='student_attendance_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.School', verbose_name='school'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student_attendance_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_attendance', to='profiles.Student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student_attendance_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='profiles.Subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='employee_attendance_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='employee_attendance_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.School', verbose_name='school'),
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student_attendance_date', 'student_attendance_subject', 'student_attendance_section', 'student_attendance_school', 'student_attendance_student')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeattendance',
            unique_together={('employee_attendance_date', 'employee_attendance_school', 'employee_attendance_employee')},
        ),
    ]
