# Generated by Django 3.0.7 on 2020-07-24 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach_staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Appointment_Subject',
            field=models.CharField(blank=True, choices=[('All Subjects', 'All Subjects'), ('Language/Languages', 'Language/Languages'), ('Mathematics', 'Mathematics'), ('Environmental Studies', 'Environmental Studies '), ('Sports', 'Sports'), ('Music', 'Music'), ('Science', 'Science'), ('Social Study', 'Social Study '), ('Accountancy', 'Accountancy'), ('Biology', 'Biology'), ('Business Studies', 'Business Studies'), ('Chemistry', 'Chemistry'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('Engineering Drawing', 'Engineering Drawing'), ('Fine Arts', 'Fine Arts'), ('Geography', 'Geography'), ('History', 'History'), ('Home Science', 'Home Science'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Political Science', 'Political Science'), ('Psychology', 'Psychology'), ('Foreign Language', 'Foreign Language'), ('Botany', 'Botany'), ('Zoology', 'Zoology'), ('Hindi', 'Hindi'), ('Sanskrit', 'Sanskrit'), ('Urdu', 'Urdu'), ('English', 'English'), ('Regional Language', 'Regional Language'), ('Art Education', 'Art Education'), ('Health and Physical Education', 'Health and Physical Education'), ('Work Education', 'Work Education'), ('Other Education', 'Other Education')], max_length=256, verbose_name='Allocated Subject'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_BRC',
            field=models.IntegerField(blank=True, null=True, verbose_name='BRC'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_CRC',
            field=models.IntegerField(blank=True, null=True, verbose_name='CRC'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Classes_Taught',
            field=models.CharField(blank=True, choices=[('Primary Only', 'Primary Only'), ('Upper Primary Only', 'Upper Primary Only'), ('Primary and Upper Primary Only', 'Primary and Upper Primary Only'), ('Secondary Only', 'Secondary Only'), ('Higher Secondary Only', 'Higher Secondary Only'), ('Upper Primary and Secondary Only', 'Upper Primary and Secondary Only'), ('Secondary and Higher Secondary Only', 'Secondary and Higher Secondary Only'), ('Pre-Primary Only', 'Pre-Primary Only'), ('Pre-Primary and Primary Only', 'Pre-Primary and Primary Only')], max_length=256, verbose_name='Classes Taught'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Code',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Contact_Number',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')], verbose_name='Phone Regex'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_DIET',
            field=models.IntegerField(blank=True, null=True, verbose_name='DIET'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Date_of_Joining',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Joining'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Disability',
            field=models.CharField(blank=True, choices=[('Not Applicable', 'Not Applicable'), ('Loco motor', 'Loco motor'), ('Visuals', 'Visuals'), ('Other', 'Other'), ('Hearing Impaired', 'Hearing Impaired')], max_length=256, verbose_name='Disability'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_English_Study_Knowledge',
            field=models.CharField(blank=True, choices=[('Below Secondary', 'Below Secondary'), ('Secondary', 'Secondary'), ('High Secondary', 'High Secondary'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate'), ('M Phil', 'M Phil'), ('Ph.D', 'Ph.D'), ('Post-Doctoral', 'Post-Doctoral')], max_length=256, verbose_name='English Knowledge'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=30, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Highest_Qualification_Academic',
            field=models.CharField(blank=True, choices=[('Below Secondary', 'Below Secondary'), ('Secondary', 'Secondary'), ('High Secondary', 'High Secondary'), ('Graduate', 'Graduate'), ('Post-Graduate', 'Post Graduate'), ('M Phil', 'M Phil'), ('Ph.D', 'Ph.D'), ('Post-Doctoral', 'Post-Doctoral')], max_length=256, verbose_name='Highest Academic Qualification'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Highest_Qualification_Professional',
            field=models.CharField(blank=True, choices=[('Diploma or basic teacher training', 'Diploma or basic teacher training'), ('Bachelor of Elementary Education', 'Bachelor of Elementary Education'), ('B.Ed or equivalent', 'B.Ed or equivalent'), ('M.Ed or equivalent', 'M.Ed or equivalent'), ('Others', 'Others'), ('None', 'None'), ('Diploma or Degree in special Education', 'Diploma or Degree in special Education'), ('Pursuing a relevant course', 'Pursuing a relevant course')], max_length=256, verbose_name='Highest Professional Qualification'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Joining_Year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Joining Year'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Language_Study_Knowledge',
            field=models.CharField(blank=True, choices=[('Below Secondary', 'Below Secondary'), ('Secondary', 'Secondary'), ('High Secondary', 'High Secondary'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate'), ('M Phil', 'M Phil'), ('Ph.D', 'Ph.D'), ('Post-Doctoral', 'Post-Doctoral')], max_length=256, verbose_name='Language Knowledge'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Main_Subject_1',
            field=models.CharField(blank=True, choices=[('All Subjects', 'All Subjects'), ('Language/Languages', 'Language/Languages'), ('Mathematics', 'Mathematics'), ('Environmental Studies', 'Environmental Studies '), ('Sports', 'Sports'), ('Music', 'Music'), ('Science', 'Science'), ('Social Study', 'Social Study '), ('Accountancy', 'Accountancy'), ('Biology', 'Biology'), ('Business Studies', 'Business Studies'), ('Chemistry', 'Chemistry'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('Engineering Drawing', 'Engineering Drawing'), ('Fine Arts', 'Fine Arts'), ('Geography', 'Geography'), ('History', 'History'), ('Home Science', 'Home Science'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Political Science', 'Political Science'), ('Psychology', 'Psychology'), ('Foreign Language', 'Foreign Language'), ('Botany', 'Botany'), ('Zoology', 'Zoology'), ('Hindi', 'Hindi'), ('Sanskrit', 'Sanskrit'), ('Urdu', 'Urdu'), ('English', 'English'), ('Regional Language', 'Regional Language'), ('Art Education', 'Art Education'), ('Health and Physical Education', 'Health and Physical Education'), ('Work Education', 'Work Education'), ('Other Education', 'Other Education')], max_length=256, verbose_name='Main Subject 1'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Main_Subject_2',
            field=models.CharField(blank=True, choices=[('All Subjects', 'All Subjects'), ('Language/Languages', 'Language/Languages'), ('Mathematics', 'Mathematics'), ('Environmental Studies', 'Environmental Studies '), ('Sports', 'Sports'), ('Music', 'Music'), ('Science', 'Science'), ('Social Study', 'Social Study '), ('Accountancy', 'Accountancy'), ('Biology', 'Biology'), ('Business Studies', 'Business Studies'), ('Chemistry', 'Chemistry'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('Engineering Drawing', 'Engineering Drawing'), ('Fine Arts', 'Fine Arts'), ('Geography', 'Geography'), ('History', 'History'), ('Home Science', 'Home Science'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Political Science', 'Political Science'), ('Psychology', 'Psychology'), ('Foreign Language', 'Foreign Language'), ('Botany', 'Botany'), ('Zoology', 'Zoology'), ('Hindi', 'Hindi'), ('Sanskrit', 'Sanskrit'), ('Urdu', 'Urdu'), ('English', 'English'), ('Regional Language', 'Regional Language'), ('Art Education', 'Art Education'), ('Health and Physical Education', 'Health and Physical Education'), ('Work Education', 'Work Education'), ('Other Education', 'Other Education')], max_length=256, verbose_name='Main Subject 2'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Marital_Status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=25, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Math_Study_Knowledge',
            field=models.CharField(blank=True, choices=[('Below Secondary', 'Below Secondary'), ('Secondary', 'Secondary'), ('High Secondary', 'High Secondary'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate'), ('M Phil', 'M Phil'), ('Ph.D', 'Ph.D'), ('Post-Doctoral', 'Post-Doctoral')], max_length=256, verbose_name='Maths Knowledge'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Nature_Of_Appointment',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Contract', 'Contract'), ('Part-Time', 'Part-Time')], max_length=256, verbose_name='Nature of Appointment'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Number_of_days_spent_on_non_teaching_assignment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of days spent on non teaching assignments'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Other_Info',
            field=models.TextField(blank=True, verbose_name='Other Information'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Science_Study_Knowledge',
            field=models.CharField(blank=True, choices=[('Below Secondary', 'Below Secondary'), ('Secondary', 'Secondary'), ('High Secondary', 'High Secondary'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate'), ('M Phil', 'M Phil'), ('Ph.D', 'Ph.D'), ('Post-Doctoral', 'Post-Doctoral')], max_length=256, verbose_name='Science Knowledge'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Social_Category',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('ORC', 'ORC'), ('OTHERS', 'OTHERS')], max_length=30, verbose_name='Social Category'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Social_Study_Knowledge',
            field=models.CharField(blank=True, choices=[('Below Secondary', 'Below Secondary'), ('Secondary', 'Secondary'), ('High Secondary', 'High Secondary'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate'), ('M Phil', 'M Phil'), ('Ph.D', 'Ph.D'), ('Post-Doctoral', 'Post-Doctoral')], max_length=256, verbose_name='Social Study Knowledge'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Trained_for_use_of_Computer',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, verbose_name='Computer Training'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Training_Need',
            field=models.CharField(blank=True, choices=[('Not Required', 'Not Required'), ('Subject Knowledge', 'Subject Knowledge'), ('Pedagogical Issues', 'Pedagogical Issues'), ('ICT skills ', 'ICT skills '), ('Knowledge and skills for CWSN', 'Knowledge and skills for CWSN'), ('Leadership and Management', 'Leadership and Management'), ('Sanitation and Hygeine', 'Sanitation and Hygeine'), ('Others', 'Others')], max_length=256, verbose_name='Training Required'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Training_Received',
            field=models.CharField(blank=True, choices=[('Not Required', 'Not Required'), ('Subject Knowledge', 'Subject Knowledge'), ('Pedagogical Issues', 'Pedagogical Issues'), ('ICT skills ', 'ICT skills '), ('Knowledge and skills for CWSN', 'Knowledge and skills for CWSN'), ('Leadership and Management', 'Leadership and Management'), ('Sanitation and Hygeine', 'Sanitation and Hygeine'), ('Others', 'Others')], max_length=256, verbose_name='Training Received'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Type',
            field=models.CharField(blank=True, choices=[('Head Teacher', 'Head Teacher'), ('Acting Head Teacher', 'Acting Head Teacher'), ('Teacher', 'Teacher'), ('Instruction Positioned Teacher', 'Instruction Positioned Teacher'), ('Principal', 'Principal'), ('Vice-Principal', 'Vice-Principal'), ('Lecturer', 'Lecturer')], max_length=256, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_info',
            name='Teacher_Validity_for_CWSN',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=256, verbose_name='Validity for CWSN'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_nonteachers_info',
            name='NonTeacher_Qualifications',
            field=models.CharField(blank=True, choices=[('Below Secondary', 'Below Secondary'), ('Secondary', 'Secondary'), ('High Secondary', 'High Secondary'), ('Graduate', 'Graduate')], max_length=50, verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_nonteachers_info',
            name='NonTeachers_Contact_Number',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_nonteachers_info',
            name='NonTeachers_Date_of_Joining',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Joining'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_nonteachers_info',
            name='NonTeachers_Date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_nonteachers_info',
            name='NonTeachers_Disability',
            field=models.CharField(blank=True, choices=[('Not Applicable', 'Not Applicable'), ('Loco motor', 'Loco motor'), ('Visuals', 'Visuals'), ('Other', 'Other'), ('Hearing Impaired', 'Hearing Impaired')], max_length=50, verbose_name='Disability'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_nonteachers_info',
            name='NonTeachers_Email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_nonteachers_info',
            name='NonTeachers_Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=30, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_nonteachers_info',
            name='NonTeachers_Joining_Year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Joining Year'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_nonteachers_info',
            name='NonTeachers_Name',
            field=models.CharField(max_length=25, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_nonteachers_info',
            name='NonTeachers_Nature_Of_Appointment',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Contract', 'Contract'), ('Part-Time', 'Part-Time')], max_length=30, verbose_name='Nature of Appointment'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_nonteachers_info',
            name='NonTeachers_Other_Info',
            field=models.TextField(blank=True, verbose_name='Other Info'),
        ),
        migrations.AlterField(
            model_name='teaching_staff_nonteachers_info',
            name='NonTeachers_Social_Category',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('ORC', 'ORC'), ('OTHERS', 'OTHERS')], max_length=30, verbose_name='Social Category'),
        ),
    ]
