# Generated by Django 3.0.8 on 2020-08-01 04:09

import django.core.validators
from django.db import migrations, models
import exams.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_test_1', exams.models.IntegerRangeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('notebook_1', exams.models.IntegerRangeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)])),
                ('sea_1', exams.models.IntegerRangeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)])),
                ('main_1', exams.models.IntegerRangeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(80)])),
                ('grade_1', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('D', 'D'), ('E', 'E'), ('NA', 'NA')], default='NA', editable=False, max_length=10)),
                ('per_test_2', exams.models.IntegerRangeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('notebook_2', exams.models.IntegerRangeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)])),
                ('sea_2', exams.models.IntegerRangeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)])),
                ('main_2', exams.models.IntegerRangeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(80)])),
                ('grade_2', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('D', 'D'), ('E', 'E'), ('NA', 'NA')], default='NA', editable=False, max_length=10)),
                ('exam_year', models.CharField(choices=[('2020-2021', '2020-2021'), ('2019-2020', '2019-2020'), ('2018-2019', '2018-2019'), ('2017-2018', '2017-2018'), ('2016-2017', '2016-2017'), ('2015-2016', '2015-2016'), ('2014-2015', '2014-2015'), ('2013-2014', '2013-2014'), ('2012-2013', '2012-2013'), ('2011-2012', '2011-2012'), ('2010-2011', '2010-2011'), ('2009-2010', '2009-2010'), ('2008-2009', '2008-2009'), ('2007-2008', '2007-2008'), ('2006-2007', '2006-2007'), ('2005-2006', '2005-2006'), ('2004-2005', '2004-2005'), ('2003-2004', '2003-2004'), ('2002-2003', '2002-2003'), ('2001-2002', '2001-2002'), ('2000-2001', '2000-2001'), ('1999-2000', '1999-2000'), ('1998-1999', '1998-1999'), ('1997-1998', '1997-1998'), ('1996-1997', '1996-1997'), ('1995-1996', '1995-1996'), ('1994-1995', '1994-1995'), ('1993-1994', '1993-1994'), ('1992-1993', '1992-1993'), ('1991-1992', '1991-1992')], default='2020-2021', max_length=50)),
                ('exam_class', models.CharField(blank=True, choices=[('1', 'CLASS 1'), ('2', 'CLASS 2'), ('3', 'CLASS 3'), ('4', 'CLASS 4'), ('5', 'CLASS 5'), ('6', 'CLASS 6'), ('7', 'CLASS 7'), ('8', 'CLASS 8'), ('9', 'CLASS 9'), ('10', 'CLASS 10'), ('11', 'CLASS 11'), ('12', 'CLASS 12'), ('LKG', 'LKG'), ('UKG', 'UKG')], max_length=5)),
                ('exam_section', models.CharField(blank=True, choices=[('', 'SECTION'), ('NA', 'NA'), ('A', 'SECTION A'), ('B', 'SECTION B'), ('C', 'SECTION C'), ('D', 'SECTION D'), ('E', 'SECTION E'), ('F', 'SECTION F')], default='NA', max_length=5)),
                ('exam_stream', models.CharField(blank=True, choices=[('', 'STREAM'), ('NA', 'NA'), ('COMMERCE', 'COMMERCE'), ('ELECTRICAL TECHNOLOGY', 'ELECTRICAL TECHNOLOGY'), ('HUMANITIES', 'HUMANITIES'), ('INFORMATION TECHNOLOGY', 'INFORMATION TECHNOLOGY'), ('PCM', 'PCM'), ('PCB', 'PCB'), ('TOURISM', 'TOURISM')], default='NA', max_length=25)),
                ('exam_rollno', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamCoScholastic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_cs_grade_1', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('NA', 'NA')], default='NA', max_length=5)),
                ('exam_cs_grade_2', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('NA', 'NA')], default='NA', max_length=5)),
                ('exam_cs_year', models.CharField(choices=[('2020-2021', '2020-2021'), ('2019-2020', '2019-2020'), ('2018-2019', '2018-2019'), ('2017-2018', '2017-2018'), ('2016-2017', '2016-2017'), ('2015-2016', '2015-2016'), ('2014-2015', '2014-2015'), ('2013-2014', '2013-2014'), ('2012-2013', '2012-2013'), ('2011-2012', '2011-2012'), ('2010-2011', '2010-2011'), ('2009-2010', '2009-2010'), ('2008-2009', '2008-2009'), ('2007-2008', '2007-2008'), ('2006-2007', '2006-2007'), ('2005-2006', '2005-2006'), ('2004-2005', '2004-2005'), ('2003-2004', '2003-2004'), ('2002-2003', '2002-2003'), ('2001-2002', '2001-2002'), ('2000-2001', '2000-2001'), ('1999-2000', '1999-2000'), ('1998-1999', '1998-1999'), ('1997-1998', '1997-1998'), ('1996-1997', '1996-1997'), ('1995-1996', '1995-1996'), ('1994-1995', '1994-1995'), ('1993-1994', '1993-1994'), ('1992-1993', '1992-1993'), ('1991-1992', '1991-1992')], default='2020-2021', max_length=50)),
                ('exam_cs_class', models.CharField(blank=True, choices=[('1', 'CLASS 1'), ('2', 'CLASS 2'), ('3', 'CLASS 3'), ('4', 'CLASS 4'), ('5', 'CLASS 5'), ('6', 'CLASS 6'), ('7', 'CLASS 7'), ('8', 'CLASS 8'), ('9', 'CLASS 9'), ('10', 'CLASS 10'), ('11', 'CLASS 11'), ('12', 'CLASS 12'), ('LKG', 'LKG'), ('UKG', 'UKG')], max_length=5)),
                ('exam_cs_section', models.CharField(blank=True, choices=[('', 'SECTION'), ('NA', 'NA'), ('A', 'SECTION A'), ('B', 'SECTION B'), ('C', 'SECTION C'), ('D', 'SECTION D'), ('E', 'SECTION E'), ('F', 'SECTION F')], default='NA', max_length=5)),
                ('exam_cs_stream', models.CharField(blank=True, choices=[('', 'STREAM'), ('NA', 'NA'), ('COMMERCE', 'COMMERCE'), ('ELECTRICAL TECHNOLOGY', 'ELECTRICAL TECHNOLOGY'), ('HUMANITIES', 'HUMANITIES'), ('INFORMATION TECHNOLOGY', 'INFORMATION TECHNOLOGY'), ('PCM', 'PCM'), ('PCB', 'PCB'), ('TOURISM', 'TOURISM')], default='NA', max_length=25)),
                ('exam_cs_rollno', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
